version: '3.4'

services:
  postgres:
    container_name: threads-db
    image: postgres
    ports:
      - "5432:5432"             # ✅ Correct: use "-" and quotes are optional but recommended
    volumes:
      - postgres_data:/var/lib/postgresql/data   # ✅ Fixed typo in path
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data:               # ✅ Define named volume at the bottom
